### ISSUE TITLE
fetcher event.js Unhandled 'error' event 和一处文档错误

### ISSUE THREAD

**Issue by monsterxcn** [JAVClub/docker#1]
(我又来提 issue 了

使用这个项目重新装了一遍，种子抓取正常，但是 fetcher loglevel:dubug 日志报错并不断尝试重启：

```
[2020-05-14T06:09:21.536] [DEBUG] Pull: Init - Handling content
[2020-05-14T06:09:21.537] [INFO] Pull: Init - [OneJAV: 0] Job finished, setting timer
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/usr/app/src/pull/../../tmp/torrents/d6ee49ceffa32135e0dc967d610fe74e3df9e7c1463cee443625b51598d398fc.torrent.tmp'
Emitted 'error' event on WriteStream instance at:
    at WriteStream.onerror (_stream_readable.js:747:14)
    at WriteStream.emit (events.js:321:20)
    at internal/fs/streams.js:397:14
    at FSReqCallback.oncomplete (fs.js:154:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/app/src/pull/../../tmp/torrents/d6ee49ceffa32135e0dc967d610fe74e3df9e7c1463cee443625b51598d398fc.torrent.tmp'
}
[2020-05-14T06:09:25.519] [DEBUG] Handle: Init - [Check torrent status] Starting job
```

没看懂这是啥问题，JAVClub_docker/fetcher/tmp 目录是可写的啊，但是目录下只有一个 downloads 空文件夹，于是我在 tmp 目录下手动新建了一个 torrents 文件夹并给了 777 权限，现在貌似一切正常。

如果这是正常情况请关闭 issue。

另外文档中那个 fetcher remote 配置里写的大小写有问题：

```
"driver": "Onejav"    ==>    "driver": "OneJAV"
```

**Comment by LynMoe** [comment]
Fixed in 3cfaf6819e9be8622ca7fc691c566691fbca5c6c

顺便问一句手动创建之后 `./tmp/sync` 最终有文件出来么

**Comment by monsterxcn** [comment]
emmm...  sync 好像并没有，qbittorrent 队列派了两千多的种子，下载完成的只有二十个，downloads 文件夹能看到视频文件。

我刚才在 qbittorrent WebUI 删掉了所有的种子，重新启动了 qbittorrent 和 fetcher，现在看到 fetcher 日志报错：

```
[2020-05-16T07:05:31.854] [DEBUG] Handle: Init - [Check torrent status] Starting job
[2020-05-16T07:05:31.854] [INFO] Module: Qbittorrent - Getting torrent list
[2020-05-16T07:05:31.855] [DEBUG] Module: Qbittorrent - GET /api/v2/torrents/info?limit=5&category=JAVClub&filter=paused&sort=completion_on&reverse=true
[2020-05-16T07:05:31.855] [DEBUG] Module: Qbittorrent - GET data:  {
  method: 'GET',
  headers: { Cookie: 'SID=G5gWU4HB0CmkK0R/Qu4C/CVC8PdRkw4s' }
}
[2020-05-16T07:05:31.861] [DEBUG] Module: Qbittorrent - GET response body []
[2020-05-16T07:05:31.861] [INFO] Handle: Init - [Check torrent status] Job finished, setting timer
[2020-05-16T07:05:59.342] [DEBUG] Pull: Init - [Download queue] Starting job
[2020-05-16T07:05:59.365] [INFO] Module: Qbittorrent - Adding category JAVClub
[2020-05-16T07:05:59.366] [DEBUG] Module: Qbittorrent - POST /api/v2/torrents/createCategory
[2020-05-16T07:05:59.366] [DEBUG] Module: Qbittorrent - POST data:  {
  method: 'POST',
  body: URLSearchParams { 'category' => 'JAVClub', 'savePath' => 'JAVClub' },
  headers: { Cookie: 'SID=G5gWU4HB0CmkK0R/Qu4C/CVC8PdRkw4s' }
}
[2020-05-16T07:05:59.371] [DEBUG] Module: Qbittorrent - POST response body Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: true,
      _transformState: [Object],
      [Symbol(kCapture)]: false
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'http://qbittorrent:8585/api/v2/torrents/createCategory',
    status: 409,
    statusText: 'Conflict',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
[2020-05-16T07:05:59.372] [INFO] Pull: Init - Handling MIGD-741, hash 4bd3d07142fc10f9efe44c6d7e8fc2e4cea52406056a8fbcd3b1e7085c247ee8
[2020-05-16T07:05:59.373] [DEBUG] Pull: Init - [MIGD-741] Parsing torrent info
[2020-05-16T07:05:59.374] [ERROR] Pull: Init - [Download queue] Job threw an error Error: not a number: buffer[0] = 10
    at getIntFromBuffer (/usr/app/node_modules/bencode/lib/decode.js:44:11)
    at Function.decode.buffer (/usr/app/node_modules/bencode/lib/decode.js:160:16)
    at Function.decode.next (/usr/app/node_modules/bencode/lib/decode.js:100:21)
    at Object.decode (/usr/app/node_modules/bencode/lib/decode.js:83:17)
    at decodeTorrentFile (/usr/app/node_modules/parse-torrent/index.js:110:23)
    at parseTorrent (/usr/app/node_modules/parse-torrent/index.js:35:12)
    at contentHandler (/usr/app/src/pull/init.js:110:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /usr/app/src/pull/init.js:142:5
    at async runAndSetInterval (/usr/app/src/pull/init.js:24:25)
[2020-05-16T07:05:59.374] [INFO] Pull: Init - [Download queue] Job finished, setting timer
```

抓取的 remote 只设置了一个 OneJAV 的 popular 那个。

**Comment by LynMoe** [comment]
现在系统只监测已完成下载并暂停的种子, 不知道你有没有在 qBittorrent 里面设置做种时间/比率限制, 或者你直接手动将已经下载完成的种子暂停也可以

上面的报错应该是抓取的某个种子不规范导致解析不了, 忽略就行

**Comment by LynMoe** [comment]
自己通过 Docker 部署了一遍, 应该把坑和问题都踩完了, 现在已经可以正常生成内容, 可以根据 `fetcher` 和 `docker` 最新几个 commit 再部署一遍

**Comment by LynMoe** [comment]
This issue is closed due to not being active. Please feel free to open it again or create a new one and reference this if you have further questions.
