### ISSUE TITLE
前端无法登录，log如下 mysql连接问题 但是phpmyadmin正常

### ISSUE THREAD

**Issue by kalagxw** [JAVClub/docker#6]
[2020-08-09T21:39:18.270] [INFO] API: Main - [UID: -1] POST /api/auth/login
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (/usr/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/usr/app/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/usr/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/app/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/usr/app/node_modules/mysql/lib/Connection.js:523:10)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:548:15)
    --------------------
    at Protocol._enqueue (/usr/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/usr/app/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/usr/app/node_modules/mysql/lib/Connection.js:116:18)
    at /usr/app/node_modules/knex/lib/dialects/mysql/index.js:68:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/usr/app/node_modules/knex/lib/dialects/mysql/index.js:63:12)
    at create (/usr/app/node_modules/knex/lib/client.js:289:39)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by kalagxw** [comment]
验证插件选mysql自带 完毕
