### ISSUE TITLE
数据库无法查表

### ISSUE THREAD

**Issue by sunkashing** [JAVClub/docker#7]
这是我的core log：
`[2020-08-19T06:28:14.554] [INFO] API: Main - JAVClub core is listening on port 3000!
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Undefined binding(s) detected when compiling FIRST. Undefined column(s): [id] query: select * from `drivers` where `isEnable` = ? and `id` = ? limit ?
    at QueryCompiler_MySQL.toSQL (/usr/app/node_modules/knex/lib/query/compiler.js:101:13)
    at Builder.toSQL (/usr/app/node_modules/knex/lib/query/builder.js:77:44)
    at /usr/app/node_modules/knex/lib/runner.js:31:36
    at /usr/app/node_modules/knex/lib/runner.js:260:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Stack.getInstance (/usr/app/src/module/stack.js:21:20)
    at async /usr/app/src/import/init.js:21:22`

但是mysql里已经有drivers的一条数据了
![image](https://user-images.githubusercontent.com/39303410/90572830-faec2700-e182-11ea-8781-16e1704c7c87.png)
不是很清楚为什么还是显示id column找不到

**Comment by LynMoe** [comment]
请检查配置文件是否按要求填写
