### ISSUE TITLE
fetcher 解析 rss 错误，并且无法移动到 sync 目录

### ISSUE THREAD

**Issue by Kherrisan** [JAVClub/docker#9]
我尝试搭建 fetcher，目前的情况是：qBittorent 可以正常下载种子，mp4 文件保存在 downloads 目录下。
出现的问题有：

### fetcher 解析 rss 错误：

（以下日志是从 docker container logs 得到的）

```
[2020-10-10T11:41:54.010] [INFO] Module: runAndSetInterval - [OneJAV: 1] Starting job
[2020-10-10T11:41:54.617] [INFO] Module: runAndSetInterval - [RSS: 0] Starting job
[2020-10-10T11:41:55.306] [ERROR] Module: runAndSetInterval - [RSS: 0] Job threw an error Error: Unable to parse XML.
    at /usr/app/node_modules/rss-parser/lib/parser.js:35:25
    at Parser.<anonymous> (/usr/app/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:321:20)
    at SAXParser.onend (/usr/app/node_modules/xml2js/lib/parser.js:131:26)
    at emit (/usr/app/node_modules/sax/lib/sax.js:624:35)
    at end (/usr/app/node_modules/sax/lib/sax.js:667:5)
    at SAXParser.write (/usr/app/node_modules/sax/lib/sax.js:975:14)
    at SAXParser.close (/usr/app/node_modules/sax/lib/sax.js:157:38)
    at Parser.exports.Parser.Parser.parseString (/usr/app/node_modules/xml2js/lib/parser.js:323:42)
    at Parser.parseString (/usr/app/node_modules/xml2js/lib/parser.js:5:59)
[2020-10-10T11:41:55.307] [INFO] Module: runAndSetInterval - [RSS: 0] Job finished, setting timer
[
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false }
]
[2020-10-10T11:41:57.065] [INFO] Module: runAndSetInterval - [OneJAV: 1] Job finished, setting timer
[2020-10-10T11:42:09.717] [INFO] Module: runAndSetInterval - [Download queue] Starting job
[2020-10-10T11:42:09.790] [INFO] Module: runAndSetInterval - [Download queue] Job finished, setting timer
```

### 下好的 mp4 文件都堆积在 downloads 目录下，sync 目录下始终没有内容

关于这个问题我没有找到日志的输出。不知道这个问题会不会受上面那个问题影响。

### 有关修改做种端口的问题

我在 qBittorrent 的 web 界面中尝试修改，发现每次修改设置项，点击 save 之后都没有反应。他会提示：

```
Unable to save program preferences, qBittorrent is probably unreachable.
```

然后我就去 fetcher/config/qBittorent/qbittorent/qBittorrent.conf 里改了 port，倒是生效了。

此外，

> 注意1: 这个版本的 fetcher 使用 qBittorrent 自带的种子管理器来判断是否已做完种, 所以请在选项 -> BitTorrent 中按照你的需求勾选做种限制中的任意一项(或两项一起) 

这句话我也不是很理解，在 options 里面也找不到意思相近的配置项。。。

**Comment by Kherrisan** [comment]
我明白了，首先 rss 的问题先不管，我把 rss 去掉了。
fetcher 应该是在 mp4 做种完成之后才会把 mp4 移动到 sync 目录下，所以可以通过限制做种率来缩短做种时间，这样 mp4 就会更快地被移到 sync 下。这样对于硬盘较小的 vps 比较好。
save preference 失败的问题有可能和我开的代理有问题，有的代理规则会把一些含有 torrent 关键字的 url 过滤掉。
